# ============================================
# Auth Service Configuration
# ============================================

server:
  port: 8085

spring:
  application:
    name: auth-service

  # -----------------------------
  # Database (PostgreSQL)
  # -----------------------------
  datasource:
    url: jdbc:postgresql://postgres:5432/krypto
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    # Username and password come from Vault:
    # secret/auth-service -> spring.datasource.username
    # secret/auth-service -> spring.datasource.password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  # -----------------------------
  # JPA / Hibernate
  # -----------------------------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# -----------------------------
# Security Settings
# -----------------------------
# JWT secret and other security keys come from Vault:
# secret/auth-service -> jwt.secret
# secret/auth-service -> jwt.expiration

jwt:
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days