# ============================================
# Gateway Service Configuration
# ============================================

server:
  port: 8080

spring:
  application:
    name: gateway

  # -----------------------------
  # Cloud Gateway Configuration
  # -----------------------------
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback/service
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@ipKeyResolver}"

      # Service discovery
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      # Route definitions
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        # Add more routes here as you add services
        # - id: user-service
        #   uri: lb://USER-SERVICE
        #   predicates:
        #     - Path=/api/v1/users/**

# -----------------------------
# Circuit Breaker (Resilience4j)
# -----------------------------
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      defaultCircuitBreaker:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 3s

# -----------------------------
# CORS Configuration
# -----------------------------
# Note: Main CORS is in application.yml (management endpoints)
# This is for gateway-specific CORS if needed
